### PR TITLE
background color was set to black when changing view

### PR DESCRIPTION
**Pull request by samhmcg5**
but in stylesheet in UI we set it to charcoal gray. I think this was an accident so I removed the setting to black. Now it is always dark gray

### CODE REVIEW

**Review by erichahn — APPROVED** [review]
Let's try it

**Comment by samhmcg5** [comment]
I'm fine if we want it black, just dont want conflicting colors between UI stylesheet and stylesheet parameters we add via cpp code

**Comment by erichahn** [comment]
Agree with that. Initial startup screens have a black background. We'll see how it looks and change if Gordon/others deem necessary.

**Comment by samhmcg5** [comment]
Ahh so the Qt bg color is gray BUT the image bg color is black as is the race view. With that in mind we probably want to change the stylesheet to be black everywhere

**Pull request merged**
