### PR TITLE
Ros setup

### PR DESCRIPTION
**Pull request by trease**
Updated CMakeLists.txt path's and added executables 
Added empty files to file in with bolt3's can messages later
created an empty telemetry package for xbee's

### CODE REVIEW

**Review by erichahn — CHANGES_REQUESTED** [review]
This appears to show fake data, not reading from can?  Is this expected? Take a look at the current setup on master. May need to pull changes into this before pushing to master.

**Comment by trease** [comment]
Its setup to display fake data on the qt side. Sam and I need to meet and test the integration now that the CAN bus works again.

**Comment by erichahn** [comment]
Let's make sure it's setup to read can data before pushing into master

**Comment by trease** [comment]
I was going to make another branch for that, does that make more sense or should i just continue to work on this one?

**Comment by erichahn** [comment]
whatever is easier and quicker for you to implement. Master is what will be on the bike very soon, so we'll want it reading can data

**Comment by trease** [comment]
I guess I'd rather setup a new branch for the next step.

**Pull request closed without merging**
